#!/bin/sh

wget -qO - https://package.perforce.com/perforce.pubkey | sudo apt-key add -
echo "deb http://package.perforce.com/apt/ubuntu trusty release" > /etc/apt/sources.list.d/perforce.list
sudo apt-get update
sudo apt-get install helix-p4d
sudo adduser perforce
sudo mkdir /perforce_depot
sudo chown perforce /perforce_depot
sudo mkdir /var/log/perforce
sudo chown perforce /var/log/perforce
sudo apt-get install daemon
cd /etc/init.d
wget https://raw.githubusercontent.com/Allar/linux-perforce-installer/master/p4dservice
chmod +x /etc/init.d/p4dservice
sudo update-rc.d p4dservice defaults
sudo reboot
